# Generated by Django 3.0.2 on 2020-02-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='Enter Your Full Name')),
                ('email', models.EmailField(default='', max_length=254)),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='LoginForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20, verbose_name='Enter Your Full Name')),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('mobile', models.PositiveIntegerField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=12)),
                ('confirm_password', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(default='', max_length=20, unique=True)),
                ('doc_name', models.CharField(choices=[('Adhaar Card', 'Adhaar Card'), ('Driving License', 'Driving License'), ('PAN Card', 'PAN Card'), ('Vehicle RC', 'Vehicle RC')], default='Adhaar Card', max_length=20)),
                ('doc_upload_front', models.ImageField(blank=True, upload_to='media/')),
                ('doc_upload_back', models.ImageField(blank=True, upload_to='media/')),
                ('qrcode', models.ImageField(blank=True, default='media/smita.jpg', upload_to='media/')),
            ],
        ),
    ]
