# Generated by Django 3.0.2 on 2020-02-14 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifydocument',
            name='user_data',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.LoginForm'),
        ),
    ]
