# Generated by Django 2.2.1 on 2020-02-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_verifydocument_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifydocument',
            name='qrcode',
            field=models.ImageField(blank=True, default='', upload_to='media/'),
        ),
    ]
