# Generated by Django 2.2.1 on 2020-03-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_ememomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='rcDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicletype', models.CharField(default='', max_length=20)),
                ('vehicleno', models.CharField(default='', max_length=25)),
                ('vehiclemake', models.CharField(default='', max_length=25)),
                ('vehiclemodel', models.CharField(default='', max_length=25)),
                ('chassisno', models.CharField(default='', max_length=25)),
                ('regdate', models.DateField()),
                ('owner_name', models.CharField(default='', max_length=30)),
                ('regvalidity', models.DateField()),
                ('address', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ememoModel',
        ),
    ]
