# Generated by Django 3.0.4 on 2020-04-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_ememo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ememo',
        ),
        migrations.DeleteModel(
            name='rcDetails',
        ),
    ]
