# Generated by Django 2.1.5 on 2020-04-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200411_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginform',
            name='dob',
            field=models.CharField(max_length=50),
        ),
    ]
