# Generated by Django 3.0.5 on 2020-04-26 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20200412_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifydocument',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verifydocument',
            name='unique',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
