# Generated by Django 3.0.5 on 2020-04-26 21:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20200426_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifydocument',
            name='unique',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
