# Generated by Django 3.0.5 on 2020-04-26 23:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20200426_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifydocument',
            name='status',
        ),
        migrations.RemoveField(
            model_name='verifydocument',
            name='unique',
        ),
        migrations.AddField(
            model_name='loginform',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Access:'),
        ),
        migrations.AddField(
            model_name='loginform',
            name='unique',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
