# Generated by Django 2.1.5 on 2020-05-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20200426_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginform',
            name='hint',
            field=models.CharField(blank=True, default='user', max_length=50),
        ),
    ]
